---
# https://docs.rke2.io/known_issues

- name: Gather system facts
  ansible.builtin.setup:

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Check if firewalld package is installed
  ansible.builtin.package_facts:
    manager: auto

- name: Stop and disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - ansible_service_mgr == "systemd"
    - "'firewalld' in ansible_facts.packages"

# If NetworkManager is installed and enabled on your hosts, 
# ensure that it is configured to ignore CNI-managed interfaces.
# https://docs.rke2.io/known_issues#networkmanager
- name: Update rke2-canal configuration when NetworkManager
  become: true
  ansible.builtin.blockinfile:
    path: /etc/NetworkManager/conf.d/rke2-canal.conf
    block: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:flannel*
    create: true
    mode: 0600
  when: "'NetworkManager.service' in ansible_facts.services"