---

- name: Wait for Kubernetes API
  wait_for:
    port: 6443
    timeout: 360

- name: Add cert-manager helm repo
  kubernetes.core.helm_repository:
    repo_url: "{{ cert_manager_helm_repo_url | default('https://charts.jetstack.io')}}"
    name: "{{ cert_manager_helm_repo_name | default('jetstack') }}"

- name: Deploy cert-manager helm chart
  shell: >
    helm upgrade {{ cert_manager_release | default('cert-manager') }} {{ cert_manager_helm_chart_ref | default('jetstack/cert-manager') }} --install --atomic --create-namespace --namespace {{ cert_manager_namespace | default('cert-manager')}} --set installCRDs=true
  register: cert_manager_install_result
  retries: 10
  delay: 30
  until: cert_manager_install_result.rc == 0

- name: Wait for cert-manager to be rolled out
  shell: >
    kubectl -n {{ cert_manager_namespace | default('cert-manager') }} rollout status deploy/{{ cert_manager_release | default('cert-manager')}} --timeout=120s
  register: cert_manager_rollout_result
  retries: 10
  delay: 30
  until: "'successfully rolled out' in cert_manager_rollout_result.stdout"