- name: Pre-Check all hosts and Register
  hosts: all
  gather_facts: true
  tasks:
    - name: Debug facts
      ansible.builtin.debug:
        msg:
          - "ansible_os_family = {{ ansible_os_family }}"
          - "ansible_distribution = {{ ansible_distribution }}"
      
    - name: Fail if not SUSE family
      ansible.builtin.assert:
        that:
          - ansible_os_family == 'Suse' or ansible_distribution == 'SL-Micro'
        fail_msg: "Supported only on SUSE family operating systems."
        success_msg: "This is a supported SUSE system."

    - name: Registration
      ansible.builtin.import_role:
        name: registration
